baseURL = 'https://ammit.org/'
languageCode = 'en-us'
title = 'Ammit | Secure Identity & MPC Solutions'

[params]
  description = "Hackproof identity solutions using MPC."

[menu]
  [[menu.main]]
    name = "Digital Identity"
    url = "/digital-identity/"
    weight = 1
  [[menu.main]]
    name = "Ammit Wallet"
    url = "/ammit-wallet/"
    weight = 2
  [[menu.main]]
    name = "Enterprise"
    url = "/enterprise-services/"
    weight = 3
  [[menu.main]]
    name = "About Us"
    url = "/about-us/"
    weight = 4
  [[menu.main]]
    name = "Join Us"
    url = "/join-us/"
    weight = 5

[caches]
  [caches.images]
    dir = ':cacheDir/images'